// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: proto/bracket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchId          int32                  `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Team1Id          *int32                 `protobuf:"varint,2,opt,name=team1_id,json=team1Id,proto3,oneof" json:"team1_id,omitempty"`
	Team2Id          *int32                 `protobuf:"varint,3,opt,name=team2_id,json=team2Id,proto3,oneof" json:"team2_id,omitempty"`
	Team1PrevMatchId *int32                 `protobuf:"varint,4,opt,name=team1_prev_match_id,json=team1PrevMatchId,proto3,oneof" json:"team1_prev_match_id,omitempty"`
	Team2PrevMatchId *int32                 `protobuf:"varint,5,opt,name=team2_prev_match_id,json=team2PrevMatchId,proto3,oneof" json:"team2_prev_match_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_bracket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *Match) GetTeam1Id() int32 {
	if x != nil && x.Team1Id != nil {
		return *x.Team1Id
	}
	return 0
}

func (x *Match) GetTeam2Id() int32 {
	if x != nil && x.Team2Id != nil {
		return *x.Team2Id
	}
	return 0
}

func (x *Match) GetTeam1PrevMatchId() int32 {
	if x != nil && x.Team1PrevMatchId != nil {
		return *x.Team1PrevMatchId
	}
	return 0
}

func (x *Match) GetTeam2PrevMatchId() int32 {
	if x != nil && x.Team2PrevMatchId != nil {
		return *x.Team2PrevMatchId
	}
	return 0
}

type MatchPosition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber    int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	VisualPosition int32                  `protobuf:"varint,2,opt,name=visual_position,json=visualPosition,proto3" json:"visual_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchPosition) Reset() {
	*x = MatchPosition{}
	mi := &file_proto_bracket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPosition) ProtoMessage() {}

func (x *MatchPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPosition.ProtoReflect.Descriptor instead.
func (*MatchPosition) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{1}
}

func (x *MatchPosition) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *MatchPosition) GetVisualPosition() int32 {
	if x != nil {
		return x.VisualPosition
	}
	return 0
}

type FetchBracketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IsSpecialUser bool                   `protobuf:"varint,2,opt,name=is_special_user,json=isSpecialUser,proto3" json:"is_special_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBracketRequest) Reset() {
	*x = FetchBracketRequest{}
	mi := &file_proto_bracket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBracketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBracketRequest) ProtoMessage() {}

func (x *FetchBracketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBracketRequest.ProtoReflect.Descriptor instead.
func (*FetchBracketRequest) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{2}
}

func (x *FetchBracketRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FetchBracketRequest) GetIsSpecialUser() bool {
	if x != nil {
		return x.IsSpecialUser
	}
	return false
}

type FetchBracketResponse struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Matches           []*Match                 `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	MatchPositions    map[int32]*MatchPosition `protobuf:"bytes,2,rep,name=match_positions,json=matchPositions,proto3" json:"match_positions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: match_id
	Predictions       map[int32]int32          `protobuf:"bytes,3,rep,name=predictions,proto3" json:"predictions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                            // key: match_id, val: winning_team_id
	IsLocked          bool                     `protobuf:"varint,4,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	TeamNames         map[int32]string         `protobuf:"bytes,5,rep,name=team_names,json=teamNames,proto3" json:"team_names,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                          // key: match_id, val: team_name
	MasterPredictions map[int32]int32          `protobuf:"bytes,6,rep,name=master_predictions,json=masterPredictions,proto3" json:"master_predictions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: match_id, val: winning_team_id
	Accuracy          *float64                 `protobuf:"fixed64,7,opt,name=accuracy,proto3,oneof" json:"accuracy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchBracketResponse) Reset() {
	*x = FetchBracketResponse{}
	mi := &file_proto_bracket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBracketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBracketResponse) ProtoMessage() {}

func (x *FetchBracketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBracketResponse.ProtoReflect.Descriptor instead.
func (*FetchBracketResponse) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{3}
}

func (x *FetchBracketResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *FetchBracketResponse) GetMatchPositions() map[int32]*MatchPosition {
	if x != nil {
		return x.MatchPositions
	}
	return nil
}

func (x *FetchBracketResponse) GetPredictions() map[int32]int32 {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *FetchBracketResponse) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *FetchBracketResponse) GetTeamNames() map[int32]string {
	if x != nil {
		return x.TeamNames
	}
	return nil
}

func (x *FetchBracketResponse) GetMasterPredictions() map[int32]int32 {
	if x != nil {
		return x.MasterPredictions
	}
	return nil
}

func (x *FetchBracketResponse) GetAccuracy() float64 {
	if x != nil && x.Accuracy != nil {
		return *x.Accuracy
	}
	return 0
}

type SubmitBracketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Predictions   map[int32]int32        `protobuf:"bytes,2,rep,name=predictions,proto3" json:"predictions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: match_id, val: winning_team_id
	IsSpecialUser bool                   `protobuf:"varint,3,opt,name=is_special_user,json=isSpecialUser,proto3" json:"is_special_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBracketRequest) Reset() {
	*x = SubmitBracketRequest{}
	mi := &file_proto_bracket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBracketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBracketRequest) ProtoMessage() {}

func (x *SubmitBracketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBracketRequest.ProtoReflect.Descriptor instead.
func (*SubmitBracketRequest) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitBracketRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SubmitBracketRequest) GetPredictions() map[int32]int32 {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *SubmitBracketRequest) GetIsSpecialUser() bool {
	if x != nil {
		return x.IsSpecialUser
	}
	return false
}

type SubmitBracketResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedBracket *FetchBracketResponse  `protobuf:"bytes,2,opt,name=updated_bracket,json=updatedBracket,proto3" json:"updated_bracket,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitBracketResponse) Reset() {
	*x = SubmitBracketResponse{}
	mi := &file_proto_bracket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBracketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBracketResponse) ProtoMessage() {}

func (x *SubmitBracketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBracketResponse.ProtoReflect.Descriptor instead.
func (*SubmitBracketResponse) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitBracketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitBracketResponse) GetUpdatedBracket() *FetchBracketResponse {
	if x != nil {
		return x.UpdatedBracket
	}
	return nil
}

type DeleteBracketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBracketRequest) Reset() {
	*x = DeleteBracketRequest{}
	mi := &file_proto_bracket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBracketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBracketRequest) ProtoMessage() {}

func (x *DeleteBracketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBracketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBracketRequest) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBracketRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteBracketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBracketResponse) Reset() {
	*x = DeleteBracketResponse{}
	mi := &file_proto_bracket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBracketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBracketResponse) ProtoMessage() {}

func (x *DeleteBracketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBracketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBracketResponse) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBracketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []string               `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTeamsRequest) Reset() {
	*x = SubmitTeamsRequest{}
	mi := &file_proto_bracket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTeamsRequest) ProtoMessage() {}

func (x *SubmitTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTeamsRequest.ProtoReflect.Descriptor instead.
func (*SubmitTeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitTeamsRequest) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

type SubmitTeamsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedBracket *FetchBracketResponse  `protobuf:"bytes,2,opt,name=updated_bracket,json=updatedBracket,proto3" json:"updated_bracket,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitTeamsResponse) Reset() {
	*x = SubmitTeamsResponse{}
	mi := &file_proto_bracket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTeamsResponse) ProtoMessage() {}

func (x *SubmitTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bracket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTeamsResponse.ProtoReflect.Descriptor instead.
func (*SubmitTeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bracket_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitTeamsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitTeamsResponse) GetUpdatedBracket() *FetchBracketResponse {
	if x != nil {
		return x.UpdatedBracket
	}
	return nil
}

var File_proto_bracket_proto protoreflect.FileDescriptor

const file_proto_bracket_proto_rawDesc = "" +
	"\n" +
	"\x13proto/bracket.proto\x12\n" +
	"h2hbracket\"\x94\x02\n" +
	"\x05Match\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\x05R\amatchId\x12\x1e\n" +
	"\bteam1_id\x18\x02 \x01(\x05H\x00R\ateam1Id\x88\x01\x01\x12\x1e\n" +
	"\bteam2_id\x18\x03 \x01(\x05H\x01R\ateam2Id\x88\x01\x01\x122\n" +
	"\x13team1_prev_match_id\x18\x04 \x01(\x05H\x02R\x10team1PrevMatchId\x88\x01\x01\x122\n" +
	"\x13team2_prev_match_id\x18\x05 \x01(\x05H\x03R\x10team2PrevMatchId\x88\x01\x01B\v\n" +
	"\t_team1_idB\v\n" +
	"\t_team2_idB\x16\n" +
	"\x14_team1_prev_match_idB\x16\n" +
	"\x14_team2_prev_match_id\"[\n" +
	"\rMatchPosition\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12'\n" +
	"\x0fvisual_position\x18\x02 \x01(\x05R\x0evisualPosition\"Y\n" +
	"\x13FetchBracketRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12&\n" +
	"\x0fis_special_user\x18\x02 \x01(\bR\risSpecialUser\"\x9c\x06\n" +
	"\x14FetchBracketResponse\x12+\n" +
	"\amatches\x18\x01 \x03(\v2\x11.h2hbracket.MatchR\amatches\x12]\n" +
	"\x0fmatch_positions\x18\x02 \x03(\v24.h2hbracket.FetchBracketResponse.MatchPositionsEntryR\x0ematchPositions\x12S\n" +
	"\vpredictions\x18\x03 \x03(\v21.h2hbracket.FetchBracketResponse.PredictionsEntryR\vpredictions\x12\x1b\n" +
	"\tis_locked\x18\x04 \x01(\bR\bisLocked\x12N\n" +
	"\n" +
	"team_names\x18\x05 \x03(\v2/.h2hbracket.FetchBracketResponse.TeamNamesEntryR\tteamNames\x12f\n" +
	"\x12master_predictions\x18\x06 \x03(\v27.h2hbracket.FetchBracketResponse.MasterPredictionsEntryR\x11masterPredictions\x12\x1f\n" +
	"\baccuracy\x18\a \x01(\x01H\x00R\baccuracy\x88\x01\x01\x1a\\\n" +
	"\x13MatchPositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.h2hbracket.MatchPositionR\x05value:\x028\x01\x1a>\n" +
	"\x10PredictionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eTeamNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16MasterPredictionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\v\n" +
	"\t_accuracy\"\xef\x01\n" +
	"\x14SubmitBracketRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12S\n" +
	"\vpredictions\x18\x02 \x03(\v21.h2hbracket.SubmitBracketRequest.PredictionsEntryR\vpredictions\x12&\n" +
	"\x0fis_special_user\x18\x03 \x01(\bR\risSpecialUser\x1a>\n" +
	"\x10PredictionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"z\n" +
	"\x15SubmitBracketResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12I\n" +
	"\x0fupdated_bracket\x18\x02 \x01(\v2 .h2hbracket.FetchBracketResponseR\x0eupdatedBracket\"2\n" +
	"\x14DeleteBracketRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x15DeleteBracketResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x12SubmitTeamsRequest\x12\x14\n" +
	"\x05teams\x18\x01 \x03(\tR\x05teams\"x\n" +
	"\x13SubmitTeamsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12I\n" +
	"\x0fupdated_bracket\x18\x02 \x01(\v2 .h2hbracket.FetchBracketResponseR\x0eupdatedBracketB\"Z h2h-bracket/internal/proto;protob\x06proto3"

var (
	file_proto_bracket_proto_rawDescOnce sync.Once
	file_proto_bracket_proto_rawDescData []byte
)

func file_proto_bracket_proto_rawDescGZIP() []byte {
	file_proto_bracket_proto_rawDescOnce.Do(func() {
		file_proto_bracket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bracket_proto_rawDesc), len(file_proto_bracket_proto_rawDesc)))
	})
	return file_proto_bracket_proto_rawDescData
}

var file_proto_bracket_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_bracket_proto_goTypes = []any{
	(*Match)(nil),                 // 0: h2hbracket.Match
	(*MatchPosition)(nil),         // 1: h2hbracket.MatchPosition
	(*FetchBracketRequest)(nil),   // 2: h2hbracket.FetchBracketRequest
	(*FetchBracketResponse)(nil),  // 3: h2hbracket.FetchBracketResponse
	(*SubmitBracketRequest)(nil),  // 4: h2hbracket.SubmitBracketRequest
	(*SubmitBracketResponse)(nil), // 5: h2hbracket.SubmitBracketResponse
	(*DeleteBracketRequest)(nil),  // 6: h2hbracket.DeleteBracketRequest
	(*DeleteBracketResponse)(nil), // 7: h2hbracket.DeleteBracketResponse
	(*SubmitTeamsRequest)(nil),    // 8: h2hbracket.SubmitTeamsRequest
	(*SubmitTeamsResponse)(nil),   // 9: h2hbracket.SubmitTeamsResponse
	nil,                           // 10: h2hbracket.FetchBracketResponse.MatchPositionsEntry
	nil,                           // 11: h2hbracket.FetchBracketResponse.PredictionsEntry
	nil,                           // 12: h2hbracket.FetchBracketResponse.TeamNamesEntry
	nil,                           // 13: h2hbracket.FetchBracketResponse.MasterPredictionsEntry
	nil,                           // 14: h2hbracket.SubmitBracketRequest.PredictionsEntry
}
var file_proto_bracket_proto_depIdxs = []int32{
	0,  // 0: h2hbracket.FetchBracketResponse.matches:type_name -> h2hbracket.Match
	10, // 1: h2hbracket.FetchBracketResponse.match_positions:type_name -> h2hbracket.FetchBracketResponse.MatchPositionsEntry
	11, // 2: h2hbracket.FetchBracketResponse.predictions:type_name -> h2hbracket.FetchBracketResponse.PredictionsEntry
	12, // 3: h2hbracket.FetchBracketResponse.team_names:type_name -> h2hbracket.FetchBracketResponse.TeamNamesEntry
	13, // 4: h2hbracket.FetchBracketResponse.master_predictions:type_name -> h2hbracket.FetchBracketResponse.MasterPredictionsEntry
	14, // 5: h2hbracket.SubmitBracketRequest.predictions:type_name -> h2hbracket.SubmitBracketRequest.PredictionsEntry
	3,  // 6: h2hbracket.SubmitBracketResponse.updated_bracket:type_name -> h2hbracket.FetchBracketResponse
	3,  // 7: h2hbracket.SubmitTeamsResponse.updated_bracket:type_name -> h2hbracket.FetchBracketResponse
	1,  // 8: h2hbracket.FetchBracketResponse.MatchPositionsEntry.value:type_name -> h2hbracket.MatchPosition
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_bracket_proto_init() }
func file_proto_bracket_proto_init() {
	if File_proto_bracket_proto != nil {
		return
	}
	file_proto_bracket_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_bracket_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bracket_proto_rawDesc), len(file_proto_bracket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bracket_proto_goTypes,
		DependencyIndexes: file_proto_bracket_proto_depIdxs,
		MessageInfos:      file_proto_bracket_proto_msgTypes,
	}.Build()
	File_proto_bracket_proto = out.File
	file_proto_bracket_proto_goTypes = nil
	file_proto_bracket_proto_depIdxs = nil
}
