// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.9
//   protoc               v7.35.1
// source: bracket.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "h2hbracket";

export interface Match {
  matchId: number;
  team1Id?: number | undefined;
  team2Id?: number | undefined;
  team1PrevMatchId?: number | undefined;
  team2PrevMatchId?: number | undefined;
}

export interface MatchPosition {
  roundNumber: number;
  visualPosition: number;
}

export interface FetchBracketRequest {
  username: string;
  isSpecialUser: boolean;
}

export interface FetchBracketResponse {
  matches: Match[];
  /** key: match_id */
  matchPositions: { [key: number]: MatchPosition };
  /** key: match_id, val: winning_team_id */
  predictions: { [key: number]: number };
  isLocked: boolean;
  /** key: match_id, val: team_name */
  teamNames: { [key: number]: string };
  /** key: match_id, val: winning_team_id */
  masterPredictions: { [key: number]: number };
  accuracy?: number | undefined;
}

export interface FetchBracketResponse_MatchPositionsEntry {
  key: number;
  value: MatchPosition | undefined;
}

export interface FetchBracketResponse_PredictionsEntry {
  key: number;
  value: number;
}

export interface FetchBracketResponse_TeamNamesEntry {
  key: number;
  value: string;
}

export interface FetchBracketResponse_MasterPredictionsEntry {
  key: number;
  value: number;
}

export interface SubmitBracketRequest {
  username: string;
  /** key: match_id, val: winning_team_id */
  predictions: { [key: number]: number };
  isSpecialUser: boolean;
}

export interface SubmitBracketRequest_PredictionsEntry {
  key: number;
  value: number;
}

export interface SubmitBracketResponse {
  status: string;
  updatedBracket: FetchBracketResponse | undefined;
}

export interface DeleteBracketRequest {
  username: string;
}

export interface DeleteBracketResponse {
  status: string;
  updatedBracket: FetchBracketResponse | undefined;
}

export interface SubmitTeamsRequest {
  teams: string[];
}

export interface SubmitTeamsResponse {
  status: string;
  updatedBracket: FetchBracketResponse | undefined;
}

function createBaseMatch(): Match {
  return {
    matchId: 0,
    team1Id: undefined,
    team2Id: undefined,
    team1PrevMatchId: undefined,
    team2PrevMatchId: undefined,
  };
}

export const Match: MessageFns<Match> = {
  encode(message: Match, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.matchId !== 0) {
      writer.uint32(8).int32(message.matchId);
    }
    if (message.team1Id !== undefined) {
      writer.uint32(16).int32(message.team1Id);
    }
    if (message.team2Id !== undefined) {
      writer.uint32(24).int32(message.team2Id);
    }
    if (message.team1PrevMatchId !== undefined) {
      writer.uint32(32).int32(message.team1PrevMatchId);
    }
    if (message.team2PrevMatchId !== undefined) {
      writer.uint32(40).int32(message.team2PrevMatchId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Match {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.matchId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.team1Id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.team2Id = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.team1PrevMatchId = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.team2PrevMatchId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Match {
    return {
      matchId: isSet(object.matchId)
        ? globalThis.Number(object.matchId)
        : isSet(object.match_id)
        ? globalThis.Number(object.match_id)
        : 0,
      team1Id: isSet(object.team1Id)
        ? globalThis.Number(object.team1Id)
        : isSet(object.team1_id)
        ? globalThis.Number(object.team1_id)
        : undefined,
      team2Id: isSet(object.team2Id)
        ? globalThis.Number(object.team2Id)
        : isSet(object.team2_id)
        ? globalThis.Number(object.team2_id)
        : undefined,
      team1PrevMatchId: isSet(object.team1PrevMatchId)
        ? globalThis.Number(object.team1PrevMatchId)
        : isSet(object.team1_prev_match_id)
        ? globalThis.Number(object.team1_prev_match_id)
        : undefined,
      team2PrevMatchId: isSet(object.team2PrevMatchId)
        ? globalThis.Number(object.team2PrevMatchId)
        : isSet(object.team2_prev_match_id)
        ? globalThis.Number(object.team2_prev_match_id)
        : undefined,
    };
  },

  toJSON(message: Match): unknown {
    const obj: any = {};
    if (message.matchId !== 0) {
      obj.matchId = Math.round(message.matchId);
    }
    if (message.team1Id !== undefined) {
      obj.team1Id = Math.round(message.team1Id);
    }
    if (message.team2Id !== undefined) {
      obj.team2Id = Math.round(message.team2Id);
    }
    if (message.team1PrevMatchId !== undefined) {
      obj.team1PrevMatchId = Math.round(message.team1PrevMatchId);
    }
    if (message.team2PrevMatchId !== undefined) {
      obj.team2PrevMatchId = Math.round(message.team2PrevMatchId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Match>, I>>(base?: I): Match {
    return Match.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Match>, I>>(object: I): Match {
    const message = createBaseMatch();
    message.matchId = object.matchId ?? 0;
    message.team1Id = object.team1Id ?? undefined;
    message.team2Id = object.team2Id ?? undefined;
    message.team1PrevMatchId = object.team1PrevMatchId ?? undefined;
    message.team2PrevMatchId = object.team2PrevMatchId ?? undefined;
    return message;
  },
};

function createBaseMatchPosition(): MatchPosition {
  return { roundNumber: 0, visualPosition: 0 };
}

export const MatchPosition: MessageFns<MatchPosition> = {
  encode(message: MatchPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roundNumber !== 0) {
      writer.uint32(8).int32(message.roundNumber);
    }
    if (message.visualPosition !== 0) {
      writer.uint32(16).int32(message.visualPosition);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchPosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.roundNumber = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.visualPosition = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MatchPosition {
    return {
      roundNumber: isSet(object.roundNumber)
        ? globalThis.Number(object.roundNumber)
        : isSet(object.round_number)
        ? globalThis.Number(object.round_number)
        : 0,
      visualPosition: isSet(object.visualPosition)
        ? globalThis.Number(object.visualPosition)
        : isSet(object.visual_position)
        ? globalThis.Number(object.visual_position)
        : 0,
    };
  },

  toJSON(message: MatchPosition): unknown {
    const obj: any = {};
    if (message.roundNumber !== 0) {
      obj.roundNumber = Math.round(message.roundNumber);
    }
    if (message.visualPosition !== 0) {
      obj.visualPosition = Math.round(message.visualPosition);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MatchPosition>, I>>(base?: I): MatchPosition {
    return MatchPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchPosition>, I>>(object: I): MatchPosition {
    const message = createBaseMatchPosition();
    message.roundNumber = object.roundNumber ?? 0;
    message.visualPosition = object.visualPosition ?? 0;
    return message;
  },
};

function createBaseFetchBracketRequest(): FetchBracketRequest {
  return { username: "", isSpecialUser: false };
}

export const FetchBracketRequest: MessageFns<FetchBracketRequest> = {
  encode(message: FetchBracketRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.isSpecialUser !== false) {
      writer.uint32(16).bool(message.isSpecialUser);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBracketRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBracketRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isSpecialUser = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBracketRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      isSpecialUser: isSet(object.isSpecialUser)
        ? globalThis.Boolean(object.isSpecialUser)
        : isSet(object.is_special_user)
        ? globalThis.Boolean(object.is_special_user)
        : false,
    };
  },

  toJSON(message: FetchBracketRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.isSpecialUser !== false) {
      obj.isSpecialUser = message.isSpecialUser;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBracketRequest>, I>>(base?: I): FetchBracketRequest {
    return FetchBracketRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBracketRequest>, I>>(object: I): FetchBracketRequest {
    const message = createBaseFetchBracketRequest();
    message.username = object.username ?? "";
    message.isSpecialUser = object.isSpecialUser ?? false;
    return message;
  },
};

function createBaseFetchBracketResponse(): FetchBracketResponse {
  return {
    matches: [],
    matchPositions: {},
    predictions: {},
    isLocked: false,
    teamNames: {},
    masterPredictions: {},
    accuracy: undefined,
  };
}

export const FetchBracketResponse: MessageFns<FetchBracketResponse> = {
  encode(message: FetchBracketResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.matches) {
      Match.encode(v!, writer.uint32(10).fork()).join();
    }
    globalThis.Object.entries(message.matchPositions).forEach(([key, value]: [string, MatchPosition]) => {
      FetchBracketResponse_MatchPositionsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    globalThis.Object.entries(message.predictions).forEach(([key, value]: [string, number]) => {
      FetchBracketResponse_PredictionsEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.isLocked !== false) {
      writer.uint32(32).bool(message.isLocked);
    }
    globalThis.Object.entries(message.teamNames).forEach(([key, value]: [string, string]) => {
      FetchBracketResponse_TeamNamesEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    globalThis.Object.entries(message.masterPredictions).forEach(([key, value]: [string, number]) => {
      FetchBracketResponse_MasterPredictionsEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    if (message.accuracy !== undefined) {
      writer.uint32(57).double(message.accuracy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBracketResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBracketResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.matches.push(Match.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = FetchBracketResponse_MatchPositionsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.matchPositions[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = FetchBracketResponse_PredictionsEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.predictions[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isLocked = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = FetchBracketResponse_TeamNamesEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.teamNames[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = FetchBracketResponse_MasterPredictionsEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.masterPredictions[entry6.key] = entry6.value;
          }
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.accuracy = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBracketResponse {
    return {
      matches: globalThis.Array.isArray(object?.matches) ? object.matches.map((e: any) => Match.fromJSON(e)) : [],
      matchPositions: isObject(object.matchPositions)
        ? (globalThis.Object.entries(object.matchPositions) as [string, any][]).reduce(
          (acc: { [key: number]: MatchPosition }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = MatchPosition.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.match_positions)
        ? (globalThis.Object.entries(object.match_positions) as [string, any][]).reduce(
          (acc: { [key: number]: MatchPosition }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = MatchPosition.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      predictions: isObject(object.predictions)
        ? (globalThis.Object.entries(object.predictions) as [string, any][]).reduce(
          (acc: { [key: number]: number }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      isLocked: isSet(object.isLocked)
        ? globalThis.Boolean(object.isLocked)
        : isSet(object.is_locked)
        ? globalThis.Boolean(object.is_locked)
        : false,
      teamNames: isObject(object.teamNames)
        ? (globalThis.Object.entries(object.teamNames) as [string, any][]).reduce(
          (acc: { [key: number]: string }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.team_names)
        ? (globalThis.Object.entries(object.team_names) as [string, any][]).reduce(
          (acc: { [key: number]: string }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      masterPredictions: isObject(object.masterPredictions)
        ? (globalThis.Object.entries(object.masterPredictions) as [string, any][]).reduce(
          (acc: { [key: number]: number }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.master_predictions)
        ? (globalThis.Object.entries(object.master_predictions) as [string, any][]).reduce(
          (acc: { [key: number]: number }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      accuracy: isSet(object.accuracy) ? globalThis.Number(object.accuracy) : undefined,
    };
  },

  toJSON(message: FetchBracketResponse): unknown {
    const obj: any = {};
    if (message.matches?.length) {
      obj.matches = message.matches.map((e) => Match.toJSON(e));
    }
    if (message.matchPositions) {
      const entries = globalThis.Object.entries(message.matchPositions) as [string, MatchPosition][];
      if (entries.length > 0) {
        obj.matchPositions = {};
        entries.forEach(([k, v]) => {
          obj.matchPositions[k] = MatchPosition.toJSON(v);
        });
      }
    }
    if (message.predictions) {
      const entries = globalThis.Object.entries(message.predictions) as [string, number][];
      if (entries.length > 0) {
        obj.predictions = {};
        entries.forEach(([k, v]) => {
          obj.predictions[k] = Math.round(v);
        });
      }
    }
    if (message.isLocked !== false) {
      obj.isLocked = message.isLocked;
    }
    if (message.teamNames) {
      const entries = globalThis.Object.entries(message.teamNames) as [string, string][];
      if (entries.length > 0) {
        obj.teamNames = {};
        entries.forEach(([k, v]) => {
          obj.teamNames[k] = v;
        });
      }
    }
    if (message.masterPredictions) {
      const entries = globalThis.Object.entries(message.masterPredictions) as [string, number][];
      if (entries.length > 0) {
        obj.masterPredictions = {};
        entries.forEach(([k, v]) => {
          obj.masterPredictions[k] = Math.round(v);
        });
      }
    }
    if (message.accuracy !== undefined) {
      obj.accuracy = message.accuracy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBracketResponse>, I>>(base?: I): FetchBracketResponse {
    return FetchBracketResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBracketResponse>, I>>(object: I): FetchBracketResponse {
    const message = createBaseFetchBracketResponse();
    message.matches = object.matches?.map((e) => Match.fromPartial(e)) || [];
    message.matchPositions = (globalThis.Object.entries(object.matchPositions ?? {}) as [string, MatchPosition][])
      .reduce((acc: { [key: number]: MatchPosition }, [key, value]: [string, MatchPosition]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = MatchPosition.fromPartial(value);
        }
        return acc;
      }, {});
    message.predictions = (globalThis.Object.entries(object.predictions ?? {}) as [string, number][]).reduce(
      (acc: { [key: number]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.isLocked = object.isLocked ?? false;
    message.teamNames = (globalThis.Object.entries(object.teamNames ?? {}) as [string, string][]).reduce(
      (acc: { [key: number]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.masterPredictions = (globalThis.Object.entries(object.masterPredictions ?? {}) as [string, number][])
      .reduce((acc: { [key: number]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Number(value);
        }
        return acc;
      }, {});
    message.accuracy = object.accuracy ?? undefined;
    return message;
  },
};

function createBaseFetchBracketResponse_MatchPositionsEntry(): FetchBracketResponse_MatchPositionsEntry {
  return { key: 0, value: undefined };
}

export const FetchBracketResponse_MatchPositionsEntry: MessageFns<FetchBracketResponse_MatchPositionsEntry> = {
  encode(message: FetchBracketResponse_MatchPositionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      MatchPosition.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBracketResponse_MatchPositionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBracketResponse_MatchPositionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = MatchPosition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBracketResponse_MatchPositionsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? MatchPosition.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: FetchBracketResponse_MatchPositionsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = MatchPosition.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBracketResponse_MatchPositionsEntry>, I>>(
    base?: I,
  ): FetchBracketResponse_MatchPositionsEntry {
    return FetchBracketResponse_MatchPositionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBracketResponse_MatchPositionsEntry>, I>>(
    object: I,
  ): FetchBracketResponse_MatchPositionsEntry {
    const message = createBaseFetchBracketResponse_MatchPositionsEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? MatchPosition.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseFetchBracketResponse_PredictionsEntry(): FetchBracketResponse_PredictionsEntry {
  return { key: 0, value: 0 };
}

export const FetchBracketResponse_PredictionsEntry: MessageFns<FetchBracketResponse_PredictionsEntry> = {
  encode(message: FetchBracketResponse_PredictionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBracketResponse_PredictionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBracketResponse_PredictionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBracketResponse_PredictionsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: FetchBracketResponse_PredictionsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBracketResponse_PredictionsEntry>, I>>(
    base?: I,
  ): FetchBracketResponse_PredictionsEntry {
    return FetchBracketResponse_PredictionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBracketResponse_PredictionsEntry>, I>>(
    object: I,
  ): FetchBracketResponse_PredictionsEntry {
    const message = createBaseFetchBracketResponse_PredictionsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseFetchBracketResponse_TeamNamesEntry(): FetchBracketResponse_TeamNamesEntry {
  return { key: 0, value: "" };
}

export const FetchBracketResponse_TeamNamesEntry: MessageFns<FetchBracketResponse_TeamNamesEntry> = {
  encode(message: FetchBracketResponse_TeamNamesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBracketResponse_TeamNamesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBracketResponse_TeamNamesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBracketResponse_TeamNamesEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: FetchBracketResponse_TeamNamesEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBracketResponse_TeamNamesEntry>, I>>(
    base?: I,
  ): FetchBracketResponse_TeamNamesEntry {
    return FetchBracketResponse_TeamNamesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBracketResponse_TeamNamesEntry>, I>>(
    object: I,
  ): FetchBracketResponse_TeamNamesEntry {
    const message = createBaseFetchBracketResponse_TeamNamesEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseFetchBracketResponse_MasterPredictionsEntry(): FetchBracketResponse_MasterPredictionsEntry {
  return { key: 0, value: 0 };
}

export const FetchBracketResponse_MasterPredictionsEntry: MessageFns<FetchBracketResponse_MasterPredictionsEntry> = {
  encode(
    message: FetchBracketResponse_MasterPredictionsEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBracketResponse_MasterPredictionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBracketResponse_MasterPredictionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBracketResponse_MasterPredictionsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: FetchBracketResponse_MasterPredictionsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBracketResponse_MasterPredictionsEntry>, I>>(
    base?: I,
  ): FetchBracketResponse_MasterPredictionsEntry {
    return FetchBracketResponse_MasterPredictionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBracketResponse_MasterPredictionsEntry>, I>>(
    object: I,
  ): FetchBracketResponse_MasterPredictionsEntry {
    const message = createBaseFetchBracketResponse_MasterPredictionsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseSubmitBracketRequest(): SubmitBracketRequest {
  return { username: "", predictions: {}, isSpecialUser: false };
}

export const SubmitBracketRequest: MessageFns<SubmitBracketRequest> = {
  encode(message: SubmitBracketRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    globalThis.Object.entries(message.predictions).forEach(([key, value]: [string, number]) => {
      SubmitBracketRequest_PredictionsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    if (message.isSpecialUser !== false) {
      writer.uint32(24).bool(message.isSpecialUser);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitBracketRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitBracketRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = SubmitBracketRequest_PredictionsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.predictions[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isSpecialUser = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitBracketRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      predictions: isObject(object.predictions)
        ? (globalThis.Object.entries(object.predictions) as [string, any][]).reduce(
          (acc: { [key: number]: number }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      isSpecialUser: isSet(object.isSpecialUser)
        ? globalThis.Boolean(object.isSpecialUser)
        : isSet(object.is_special_user)
        ? globalThis.Boolean(object.is_special_user)
        : false,
    };
  },

  toJSON(message: SubmitBracketRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.predictions) {
      const entries = globalThis.Object.entries(message.predictions) as [string, number][];
      if (entries.length > 0) {
        obj.predictions = {};
        entries.forEach(([k, v]) => {
          obj.predictions[k] = Math.round(v);
        });
      }
    }
    if (message.isSpecialUser !== false) {
      obj.isSpecialUser = message.isSpecialUser;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitBracketRequest>, I>>(base?: I): SubmitBracketRequest {
    return SubmitBracketRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitBracketRequest>, I>>(object: I): SubmitBracketRequest {
    const message = createBaseSubmitBracketRequest();
    message.username = object.username ?? "";
    message.predictions = (globalThis.Object.entries(object.predictions ?? {}) as [string, number][]).reduce(
      (acc: { [key: number]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.isSpecialUser = object.isSpecialUser ?? false;
    return message;
  },
};

function createBaseSubmitBracketRequest_PredictionsEntry(): SubmitBracketRequest_PredictionsEntry {
  return { key: 0, value: 0 };
}

export const SubmitBracketRequest_PredictionsEntry: MessageFns<SubmitBracketRequest_PredictionsEntry> = {
  encode(message: SubmitBracketRequest_PredictionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitBracketRequest_PredictionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitBracketRequest_PredictionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitBracketRequest_PredictionsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: SubmitBracketRequest_PredictionsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitBracketRequest_PredictionsEntry>, I>>(
    base?: I,
  ): SubmitBracketRequest_PredictionsEntry {
    return SubmitBracketRequest_PredictionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitBracketRequest_PredictionsEntry>, I>>(
    object: I,
  ): SubmitBracketRequest_PredictionsEntry {
    const message = createBaseSubmitBracketRequest_PredictionsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseSubmitBracketResponse(): SubmitBracketResponse {
  return { status: "", updatedBracket: undefined };
}

export const SubmitBracketResponse: MessageFns<SubmitBracketResponse> = {
  encode(message: SubmitBracketResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.updatedBracket !== undefined) {
      FetchBracketResponse.encode(message.updatedBracket, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitBracketResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitBracketResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updatedBracket = FetchBracketResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitBracketResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      updatedBracket: isSet(object.updatedBracket)
        ? FetchBracketResponse.fromJSON(object.updatedBracket)
        : isSet(object.updated_bracket)
        ? FetchBracketResponse.fromJSON(object.updated_bracket)
        : undefined,
    };
  },

  toJSON(message: SubmitBracketResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.updatedBracket !== undefined) {
      obj.updatedBracket = FetchBracketResponse.toJSON(message.updatedBracket);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitBracketResponse>, I>>(base?: I): SubmitBracketResponse {
    return SubmitBracketResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitBracketResponse>, I>>(object: I): SubmitBracketResponse {
    const message = createBaseSubmitBracketResponse();
    message.status = object.status ?? "";
    message.updatedBracket = (object.updatedBracket !== undefined && object.updatedBracket !== null)
      ? FetchBracketResponse.fromPartial(object.updatedBracket)
      : undefined;
    return message;
  },
};

function createBaseDeleteBracketRequest(): DeleteBracketRequest {
  return { username: "" };
}

export const DeleteBracketRequest: MessageFns<DeleteBracketRequest> = {
  encode(message: DeleteBracketRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteBracketRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteBracketRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteBracketRequest {
    return { username: isSet(object.username) ? globalThis.String(object.username) : "" };
  },

  toJSON(message: DeleteBracketRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteBracketRequest>, I>>(base?: I): DeleteBracketRequest {
    return DeleteBracketRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteBracketRequest>, I>>(object: I): DeleteBracketRequest {
    const message = createBaseDeleteBracketRequest();
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseDeleteBracketResponse(): DeleteBracketResponse {
  return { status: "", updatedBracket: undefined };
}

export const DeleteBracketResponse: MessageFns<DeleteBracketResponse> = {
  encode(message: DeleteBracketResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.updatedBracket !== undefined) {
      FetchBracketResponse.encode(message.updatedBracket, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteBracketResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteBracketResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updatedBracket = FetchBracketResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteBracketResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      updatedBracket: isSet(object.updatedBracket)
        ? FetchBracketResponse.fromJSON(object.updatedBracket)
        : isSet(object.updated_bracket)
        ? FetchBracketResponse.fromJSON(object.updated_bracket)
        : undefined,
    };
  },

  toJSON(message: DeleteBracketResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.updatedBracket !== undefined) {
      obj.updatedBracket = FetchBracketResponse.toJSON(message.updatedBracket);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteBracketResponse>, I>>(base?: I): DeleteBracketResponse {
    return DeleteBracketResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteBracketResponse>, I>>(object: I): DeleteBracketResponse {
    const message = createBaseDeleteBracketResponse();
    message.status = object.status ?? "";
    message.updatedBracket = (object.updatedBracket !== undefined && object.updatedBracket !== null)
      ? FetchBracketResponse.fromPartial(object.updatedBracket)
      : undefined;
    return message;
  },
};

function createBaseSubmitTeamsRequest(): SubmitTeamsRequest {
  return { teams: [] };
}

export const SubmitTeamsRequest: MessageFns<SubmitTeamsRequest> = {
  encode(message: SubmitTeamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.teams) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitTeamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitTeamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.teams.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitTeamsRequest {
    return { teams: globalThis.Array.isArray(object?.teams) ? object.teams.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: SubmitTeamsRequest): unknown {
    const obj: any = {};
    if (message.teams?.length) {
      obj.teams = message.teams;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitTeamsRequest>, I>>(base?: I): SubmitTeamsRequest {
    return SubmitTeamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitTeamsRequest>, I>>(object: I): SubmitTeamsRequest {
    const message = createBaseSubmitTeamsRequest();
    message.teams = object.teams?.map((e) => e) || [];
    return message;
  },
};

function createBaseSubmitTeamsResponse(): SubmitTeamsResponse {
  return { status: "", updatedBracket: undefined };
}

export const SubmitTeamsResponse: MessageFns<SubmitTeamsResponse> = {
  encode(message: SubmitTeamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.updatedBracket !== undefined) {
      FetchBracketResponse.encode(message.updatedBracket, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitTeamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitTeamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updatedBracket = FetchBracketResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitTeamsResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      updatedBracket: isSet(object.updatedBracket)
        ? FetchBracketResponse.fromJSON(object.updatedBracket)
        : isSet(object.updated_bracket)
        ? FetchBracketResponse.fromJSON(object.updated_bracket)
        : undefined,
    };
  },

  toJSON(message: SubmitTeamsResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.updatedBracket !== undefined) {
      obj.updatedBracket = FetchBracketResponse.toJSON(message.updatedBracket);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitTeamsResponse>, I>>(base?: I): SubmitTeamsResponse {
    return SubmitTeamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitTeamsResponse>, I>>(object: I): SubmitTeamsResponse {
    const message = createBaseSubmitTeamsResponse();
    message.status = object.status ?? "";
    message.updatedBracket = (object.updatedBracket !== undefined && object.updatedBracket !== null)
      ? FetchBracketResponse.fromPartial(object.updatedBracket)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
